services:
  # Redis - Rate Limiting, 차단 시스템, 로그인 시도 추적용
  redis:
    image: redis:7-alpine
    container_name: api-gateway-redis
    ports:
      - "6380:6379"  # 포트 +1 (기본 6379 → 6380)
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - api-gateway-network

  # Kafka - Standalone 모드 (Zookeeper 내장)
  kafka:
    image: apache/kafka:latest
    container_name: api-gateway-kafka-simple
    ports:
      - "9093:9092"  # 포트 +1 (기본 9092 → 9093)
    environment:
      # Standalone 모드 설정 (Zookeeper 내장)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - kafka_data:/var/lib/kafka/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - api-gateway-network

volumes:
  redis_data:
    driver: local
  kafka_data:
    driver: local

networks:
  api-gateway-network:
    driver: bridge
    name: api-gateway-network