services:
  # Redis - Rate Limiting, 차단 시스템, 로그인 시도 추적용
  redis:
    image: redis:7-alpine
    container_name: api-gateway-redis
    ports:
      - "6380:6379"  # 포트 +1 (기본 6379 → 6380)
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - api-gateway-network

volumes:
  redis_data:
    driver: local

networks:
  api-gateway-network:
    driver: bridge
    name: api-gateway-network