# =================================================================
#                 API Gateway 공통 설정
# =================================================================
spring:
  application:
    name: api-gateway
  profiles:
    active: local
  main:
    allow-circular-references: true

  # Kafka 설정
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    producer:
      client-id: ${spring.application.name}-logging-producer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432
      compression-type: snappy
      enable-idempotence: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
      group-id: gateway-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate
    template:
      default-topic: logs.gateway

  # Redis 설정
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 5000ms
      connect-timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 3000ms
        shutdown-timeout: 100ms

  # OAuth2 / JWT 설정
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://api-bridge.us.auth0.com/
            authorization-uri: https://api-bridge.us.auth0.com/authorize
            token-uri: https://api-bridge.us.auth0.com/oauth/token
            user-info-uri: https://api-bridge.us.auth0.com/userinfo
            jwk-set-uri: https://api-bridge.us.auth0.com/.well-known/jwks.json
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI:https://api-bridge.us.auth0.com/}
          audience: ${AUTH0_AUDIENCE:http://localhost:8080/}

# Auth0 설정 (모든 프로필에서 공통 적용)
auth0:
  issuerUri: ${AUTH0_ISSUER_URI:https://api-bridge.us.auth0.com/}
  audience: ${AUTH0_AUDIENCE:http://localhost:8080/}
  client-id: ${AUTH0_CLIENT_ID}
  logout-redirect-uri: ${AUTH0_LOGOUT_REDIRECT_URI:http://localhost:8080/auth/logout-success}

# =================================================================
#                 프로필별 설정 (로컬 환경)
# =================================================================
---
spring:
  config:
    activate:
      on-profile: local


  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
            backoff:
              first-backoff: 50ms
              max-backoff: 500ms
              factor: 2
        - AddRequestHeader=X-Gateway, api-gateway
        - RemoveRequestHeader=Cookie
        - name: StandardResponseFilter
        - name: TokenRelay
        # Global Rate Limiting은 주석 처리 (라우트별로 개별 설정)
        # - name: RequestRateLimiter
        #   args:
        #     rate-limiter: "#{@defaultRedisRateLimiter}"
        #     key-resolver: "#{@userKeyResolver}"
        #     deny-empty-key: false
      routes:
        # Rate Limiting 테스트 전용 라우트 - 일시 비활성화
        # - id: ratelimit-test-route
        #   uri: http://httpbin.org
        #   predicates:
        #     - Path=/gateway/ratelimit/**
        #   filters:
        #     - name: RequestRateLimiter
        #       args:
        #         rate-limiter: "#{@defaultRedisRateLimiter}"
        #         key-resolver: "#{@userKeyResolver}"
        #         deny-empty-key: false
        #     - name: RewritePath
        #       args:
        #         regexp: /gateway/ratelimit/(?<segment>.*)
        #         replacement: /status/200
        
        # Mock 서비스 라우트들 - 일시 비활성화 (Redis 없이 실행하기 위함)
        # - id: mock-user-service
        #   uri: http://localhost:8080
        #   predicates:
        #     - Path=/mock/users/**

        # 서비스별 라우팅 설정 (로컬 환경용)
        - id: user-service-local
          uri: http://localhost:8081
          predicates:
            - Path=/gateway/users/**
          filters:
            - StripPrefix=2
            # Rate Limiting 일시 비활성화 (Redis 없이 실행하기 위함)
            # - name: RequestRateLimiter
            #   args:
            #     rate-limiter: "#{@userServiceRateLimiter}"
            #     key-resolver: "#{@userKeyResolver}"
            #     deny-empty-key: false
            - name: CircuitBreaker
              args:
                name: userSvcCb
                fallback-uri: forward:/fallback/user-service

        # 추후 포트 결정 후 활성화 예정
        # - id: api-management-service-local
        #   uri: http://localhost:8082
        #   predicates:
        #     - Path=/gateway/apimgmt/**
        #   filters:
        #     - StripPrefix=2
        #     - name: RequestRateLimiter
        #       args:
        #         rate-limiter: "#{@managementServiceRateLimiter}"
        #         key-resolver: "#{@userKeyResolver}"
        #         deny-empty-key: false
        #     - name: CircuitBreaker
        #       args:
        #         name: apiMgmtSvcCb
        #         fallback-uri: forward:/fallback/api-management

        # - id: custom-api-management-service-local
        #   uri: http://localhost:8083
        #   predicates:
        #     - Path=/gateway/customapi/**
        #   filters:
        #     - StripPrefix=2
        #     - name: RequestRateLimiter
        #       args:
        #         rate-limiter: "#{@managementServiceRateLimiter}"
        #         key-resolver: "#{@userKeyResolver}"
        #         deny-empty-key: false
        #     - name: CircuitBreaker
        #       args:
        #         name: customApiMgmtSvcCb
        #         fallback-uri: forward:/fallback/custom-api-management

        # - id: ai-feature-service-local
        #   uri: http://localhost:8084
        #   predicates:
        #     - Path=/gateway/aifeature/**
        #   filters:
        #     - StripPrefix=2
        #     - name: RequestRateLimiter
        #       args:
        #         rate-limiter: "#{@aiServiceRateLimiter}"
        #         key-resolver: "#{@userKeyResolver}"
        #         deny-empty-key: false
        #     - name: CircuitBreaker
        #       args:
        #         name: aiFeatureSvcCb
        #         fallback-uri: forward:/fallback/ai-feature

        # AI 서비스 라우트 (POST /ai/generate/custom-api)
        - id: ai-service-generate-custom-api
          uri: http://localhost:8085
          predicates:
            - Path=/ai/generate/custom-api
            - Method=POST
          filters:
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@aiServiceRateLimiter}"
                key-resolver: "#{@userKeyResolver}"
                deny-empty-key: false
            - name: CircuitBreaker
              args:
                name: aiSvcCb
                fallback-uri: forward:/fallback/ai-service

        # 커스텀 API 사용 라우트 (GET /custom/apiName={커스텀API이름})
        - id: ai-service-custom-api-usage
          uri: http://localhost:8085
          predicates:
            - Path=/custom/**
            - Method=GET
          filters:
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@aiServiceRateLimiter}"
                key-resolver: "#{@userKeyResolver}"
                deny-empty-key: false
            - name: CircuitBreaker
              args:
                name: aiSvcCb
                fallback-uri: forward:/fallback/ai-service

        # - id: system-management-service-local
        #   uri: http://localhost:8085
        #   predicates:
        #     - Path=/gateway/sysmgmt/**
        #   filters:
        #     - StripPrefix=2
        #     - name: RequestRateLimiter
        #       args:
        #         rate-limiter: "#{@managementServiceRateLimiter}"
        #         key-resolver: "#{@userKeyResolver}"
        #         deny-empty-key: false
        #     - name: CircuitBreaker
        #       args:
        #         name: systemMgmtSvcCb
        #         fallback-uri: forward:/fallback/system-management

  server:
    port: ${SERVER_PORT:8080}

# =================================================================
#                 프로필별 설정 (프로덕션 환경) - 추후 필요시 활성화
# =================================================================
# ---
# spring:
#   config:
#     activate:
#       on-profile: prod
#
#   cloud:
#     gateway:
#       routes:
#         - id: user-service
#           uri: http://production-server:8081
#           predicates:
#             - Path=/gateway/users/**
#           filters:
#             - StripPrefix=2
#             - TokenRelay=
#             - name: RequestRateLimiter
#               args:
#                 rate-limiter: "#{@userServiceRateLimiter}"
#                 key-resolver: "#{@userKeyResolver}"
#             - name: CircuitBreaker
#               args:
#                 name: userSvcCb
#                 fallback-uri: forward:/fallback/user-service

# =================================================================
#                 액추에이터 및 기타 설정 (공통)
# =================================================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,gateway,circuitbreakers
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
      show-components: always
    gateway:
      access: read_only
    circuitbreakers:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      service: api-gateway
      version: ${BUILD_VERSION:dev}
      environment: ${SPRING_PROFILES_ACTIVE:local}
    export:
      prometheus:
        descriptions: true
        histogram-flavor: prometheus
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        slowCallDurationThreshold: 3s
        slowCallRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.io.IOException
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - org.springframework.web.reactive.function.client.WebClientResponseException.ServiceUnavailable
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
          - org.springframework.web.reactive.function.client.WebClientResponseException.NotFound
    instances:
      userSvcCb:
        baseConfig: default
        registerHealthIndicator: true
      apiMgmtSvcCb:
        baseConfig: default
        registerHealthIndicator: true
      customApiMgmtSvcCb:
        baseConfig: default
        registerHealthIndicator: true
      aiFeatureSvcCb:
        baseConfig: default
        registerHealthIndicator: true
        slowCallDurationThreshold: 5s
        slowCallRateThreshold: 30
      systemMgmtSvcCb:
        baseConfig: default
        registerHealthIndicator: true
  metrics:
    enabled: true
    legacy:
      enabled: false
  prometheus:
    enabled: true

# 로깅 설정
logging:
  level:
    root: INFO
    org.example.APIGatewaySvc: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    com.nimbusds: DEBUG
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{requestId:-}] %logger{36} - %msg%n"

# 서버 설정
server:
  port: ${SERVER_PORT:8080}
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

# Gateway 로깅 설정
gateway:
  logging:
    enabled: ${GATEWAY_LOGGING_ENABLED:true}
    kafka:
      topic: ${GATEWAY_LOG_TOPIC:logs.gateway}
    mask-sensitive-data: ${GATEWAY_MASK_SENSITIVE_DATA:true}

# Kafka 기능 활성화
kafka:
  enabled: ${KAFKA_ENABLED:true}

# Rate Limiting 설정
rate-limit:
  default:
    replenish-rate: ${RATE_LIMIT_REPLENISH_RATE:10}
    burst-capacity: ${RATE_LIMIT_BURST_CAPACITY:20}
    requested-tokens: ${RATE_LIMIT_REQUESTED_TOKENS:1}
  user-service:
    replenish-rate: 20
    burst-capacity: 40
  ai-service:
    replenish-rate: 5
    burst-capacity: 10
    requested-tokens: 2
  management:
    replenish-rate: 15
    burst-capacity: 30

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true
